[package]
name = "dg_simulator"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "dg_simulator"

[dependencies]
nalgebra = "0.34"
getrandom = { version = "*", features = ["js"] }
plotly = "0.9"
wasm-bindgen = "0.2"
